### PR TITLE
Do not attempt to write ETS data to crashed process

### PR DESCRIPTION
**Pull request by davecromberge**
Not sure about the proposed fix, do you think it is better to let it crash and burn?

### CODE REVIEW

**Comment by Licenser** [comment]
I'm not sure how the change will differ in behavior, the ETS gets dumped in both cases, crashing would mean a clean slate and the knowledge of something going wrong. What is the thought behind 'hiding' the fault?

**Comment by davecromberge** [comment]
I mean that the data is not written to a metric_store process that has presumably died, possibly causing the termination of the metric_vnode.  Does the reason need to be examined? How far do we take the let it crash philosophy in this case?  I come from the point of view of the cost involved in losing vnode.  
Will the ETS tables get cleaned up "properly" if the vnode termination does not succeed?  These are grey areas for me, as I have read some articles about refc binaries and their collection.  P.S. I'm new to Erlang

**Comment by Licenser** [comment]
The ETS table will be cleaned up it's linked to the process, the code is in terminate so we're not really 'loosing' the vnode it's already going away. What I'm not 100% sure about now that you bring the topic up is what happens if a process crashes in terminate, my guess is that it just crashes and don't enters a terminate loop (that would be bad :tm:).

I will double-check if crashing in terminate behaves 'nicely' if it does I don't see a reason for defensiveness at that point, generating a crash dump on a failing process is preferable to hiding a fault in my eyes.

**Comment by davecromberge** [comment]
Ok @Licenser thanks.  Now that we are on the subject, what about guarding against errors within the metric_io process itself?  Every time that process crashes, the entire mstore with buckets and indexes needs to be GC'd and reconstructed.  What is your opinion about defensiveness in such scenarios?  Does the "cost" associated with a crash ever justify coding defensively, going against the erlang philosophy?

**Comment by Licenser** [comment]
I don't think it is, you risk getting into a 'bad' state and staying there, the beauty about let it crash is that you'll start up with a good system after a crash. The problem with defensiveness is that you might 'defend' a problematic condition and by that end up being stuck in it.

**Comment by davecromberge** [comment]
Of course, that's a very good point. I think I will close this PR, and leave the code as is. Thanks for answering my questions!

**Pull request closed without merging**
