### PR TITLE
A few Makefile improvements for easier packaging

### PR DESCRIPTION
**Pull request by 7heo**

### CODE REVIEW

**Comment by Licenser** [comment]
awesome thanks!

**Comment by 7heo** [comment]
Sorry, it's again against dev.

**Comment by Licenser** [comment]
reverted as it failed to build.

**Comment by Licenser** [comment]
```
make pre-commit
for i in rel/files/*; do (head -1 $i | grep -v sh > /dev/null) || bash -n $i || exit 1; done;
grep: apps//src/.app.src: No such file or directory
grep: apps//src/.app.src: No such file or directory
Testing against package version: 0.3.2
App version out of date
make: *** [test-vsn] Error 1
```

**Pull request merged**
