### PR TITLE
Fix a bug introduced by my last commit.

### PR DESCRIPTION
**Pull request by 7heo**

### CODE REVIEW

**Comment by Licenser** [comment]
Not all happy with the approach here. rebar already templates quite a few files so there would now be two templateings going one.

Moving `rel/vars.conf`will break builds when the makefile is not run first, that is a no-go.

**Comment by 7heo** [comment]
@Licenser, github has added commits automatically that were not meant to be in this PR. I wanted to discuss them with you beforehand. How do we handle this?

**Comment by Licenser** [comment]
pull requests work agianst branches, so the moment you added more commits to the branch it gets included in the PR.

I think the best approach is to close this, make one clean branch with makefile changes, get that working fully. Then a second branch with other changes that we can discuss.

**Comment by 7heo** [comment]
Agreed.

**Pull request closed without merging**
